# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get golib
      run: |
        ./get_golib.sh

    - name: Check dependencies
      run: |
        cd ../golib
        lastTag=$(git tag --list | tail -1)
        echo "lastTag=$lastTag"
        cd -

        for pkg in $(ls -l ../golib | grep ^d | awk '{print $9}'); do
          echo "go get github.com/CHESSComputing/golib/$pkg@$lastTag"
        done | /bin/sh

    - name: Build
      run: make

    - name: Test
      run: make test
